config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'

  ActiveAdmin.routes(self)
  get 'articles/show'

  root 'home#index'
  resources :articles, only: [:show], path: I18n.t('paths.articles').downcase
  resources :recipes, only: [:index], path: I18n.t('paths.recipes').downcase
  resources :submissions, only: [:new, :create], path: I18n.t('paths.submissions').downcase
  get 'kontakt/success', to: 'submissions#success', as: 'submission_success'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_many :article_sections
  has_one :quiz

  accepts_nested_attributes_for :article_sections, allow_destroy: true
  serialize :entryboxes, Hash

  mount_uploader :image, BannerUploader

  default_scope { order(:weight) }

  before_save :generate_slug

  def generate_slug
    self.slug = self.title.parameterize
  end

  def get_entryboxes
    boxes = {}
    types = [:quiz_entry, :exercise_entry, :wholegrain_entry, :food_entry, :recipes_entry]

    types.each do |t|
      boxes[t] = send(t)
    end

    boxes.sort_by { |_, v| -v }.reject { |_,v| v == 0 }.reverse
  end
end

app/models/article_section.rb
class ArticleSection < ActiveRecord::Base
  belongs_to :article
  default_scope { order(:weight) }

  mount_uploader :image, SectionUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  has_many :quizzes

  default_scope { order(:weight) }
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  default_scope { order(:weight) }
  mount_uploader :image, RecipeUploader

  belongs_to :recipe_category
end

app/models/recipe_category.rb
class RecipeCategory < ActiveRecord::Base
  has_many :recipes

  default_scope { order(:weight) }
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  validates :school_name, :contact_person, :address, :zip, :city, :email, :class_level, :students, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    unless session[:user_id].present?
      redirect_to login_path
    end
  end

  helper_method :current_user
  def current_user
    User.find(session[:user_id]) if session[:user_id].present?
  end

  def authorize
    redirect_to login_url, warning: 'Not authorized' if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    unless params[:id].is_number?
      @article = Article.find_by_slug(params[:id])
    end
    @article ||= Article.find params[:id]

    raise ActiveRecord::RecordNotFound.new if @article.nil?

    @active_cat = @article.category
    @quiz = @article.quiz
    @quiz ||= @article.category.quizzes.order("RANDOM()").first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authorize, except: [:new, :create]

  def new
  end

  def create
    user = User.find_by_name(session_params[:name])
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to admin_root_path, success: "Welcome, #{user.name}"
    else
      flash.now[:error] = 'Invalid password or email'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, success: 'You have been logged out'
  end

  private

  def session_params
    params.require(:session).permit(:name, :password)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(submission_params)

    if @submission.save
      redirect_to submission_success_path
    else
      render 'new'
    end
  end

  def success
  end

  def submission_params
    params.require(:submission).permit(:school_name, :contact_person, :address, :zip, :city, :email, :class_level, :students, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<%= image_tag @article.image_url %>

<% unless @article.sub_title.empty? %><h2><%= @article.sub_title %></h2><% end %>
<p><%= @article.body.html_safe %></p>


<% @article.article_sections.each do |section| %>
  <div class="text-section">
    <% if section.image_position == 'Left' %>
      <div class="text-section__left"><%= image_tag section.image_url(:small) %></div>
      <div class="text-section__right">
        <h3><%= section.header %></h3>
        <p><%= section.body.html_safe %></p>
      </div>
    <% elsif section.image_position == 'Right' %>
      <div class="text-section__left">
        <h3><%= section.header %></h3>
        <p><%= section.body.html_safe %></p>
      </div>
      <div class="text-section__right"><%= image_tag section.image_url(:small) %></div>
    <% elsif section.image_position == 'Full' %>
      <div class="text-section__full"><%= image_tag section.image_url(:full) %></div>
      <div class="text-section__full">
        <h3><%= section.header %></h3>
        <p><%= section.body.html_safe %></p>
      </div>
    <% elsif section.image_position == 'No image' %>
      <div class="text-section__full">
        <h3><%= section.header %></h3>
        <p><%= section.body.html_safe %></p>
      </div>
    <% end %>
  </div>
<% end %>

<% content_for :aside do %>
  <% if @quiz.present? %>
    <div class="quiz">

      <div class="quiz__body quiz__body--init">
        <p><%= @quiz.question %></p>

        <span id="answer" style="display: none" data-answer="<%= @quiz.correct_answer %>"></span>
        <div class="color-entry-box__button quiz__answer" data-answer="1"><%= @quiz.answer_1 %></div>
        <div class="color-entry-box__button quiz__answer" data-answer="2"><%= @quiz.answer_2 %></div>
        <div class="color-entry-box__button quiz__answer" data-answer="3"><%= @quiz.answer_3 %></div>
      </div>

      <div class="quiz__body quiz__body--correct">
        <p>Det er helt rigtigt! <br> Du er super cool</p>
      </div>

      <div class="quiz__body quiz__body--wrong">
        <p>Øv, det er desværre ikke helt rigtigt!</p>

        <span>Prøv igen</span>
      </div>
    </div>
  <% end %>

  <% @article.get_entryboxes.each do |k, _| %>

    <% if k == :quiz_entry %>
      <a href="/artikel/madpakkequiz">
        <div class="color-entry-box color-entry-box--small color-entry-box--lunch-quiz">
        </div>
      </a>
    <% end %>

    <% if k == :exercise_entry %>
      <a href="/artikel/motion">
        <div class="color-entry-box color-entry-box--small color-entry-box--blue">
          <h3>Motion</h3>
        </div>
      </a>
    <% end %>

    <% if k == :wholegrain_entry %>
      <a href="/artikel/hvad-er-fuldkorn">
        <div class="color-entry-box color-entry-box--small color-entry-box--red">
          <h3>Fuldkorn</h3>
        </div>
      </a>
    <% end %>

    <% if k == :food_entry %>
      <a href="/artikel/energifordeling">
        <div class="color-entry-box color-entry-box--small color-entry-box--green">
          <h3>Maden du<br> spiser</h3>
        </div>
      </a>
    <% end %>

    <% if k == :recipes_entry %>
      <a href="/opskrifter">
        <div class="color-entry-box color-entry-box--small color-entry-box--recipes">
          <h3>Se Opskrifter</h3>
        </div>
      </a>
    <% end %>
  <% end %>

  <div class="blank"></div>
<% end %>

app/views/home/index.html.erb
<% content_for :full_width do %>
  <div class="top-banner">
    <h1 class="top-banner__title">Fokus på<br> det sunde måltid<br> midt på dagen</h1>
  </div>
<% end %>

<div class="col--50">
  <div class="color-entry-box color-entry-box--red">
    <h3>Fuldkorn</h3>
    <p>Lær hvordan man udnytter kornet<br> på den bedste måde</p>
    <a href="/artikel/hvad-er-fuldkorn" class="color-entry-box__button">Læs mere her</a>
  </div>

  <div style="height: 370px;" class="color-entry-box color-entry-box--girl">
    <a href="/artikel/madpakkequiz" class="color-entry-box__button">Madpakkequiz</a>
  </div>

  <div style="height: 340px;" class="color-entry-box color-entry-box--green">
    <h3>Maden du spiser</h3>
    <p>Har du brug for både<br> kulhydrat, protein og fedt?</p>
    <a href="/artikel/energifordeling" class="color-entry-box__button">Lær mere her</a>
  </div>
</div>


<div class="col--50">
  <div style="height: 350px;" class="color-entry-box color-entry-box--blue">
    <h3>Motion</h3>
    <p>Hvorfor skal vi bevæge os <br> og dyrke motion?</p>
    <a href="/artikel/motion" class="color-entry-box__button">Bliv klogere her</a>
  </div>

  <div style="height: 268px;" class="color-entry-box color-entry-box--brown">
    <h3>Til læreren</h3>
    <p>Lærervejledning og<br> supplerende opgaver</p>
    <a href="/artikel/kaere-underviser" class="color-entry-box__button">Se her</a>
  </div>

  <a href="/opskrifter">
    <div class="color-entry-box color-entry-box--food">
      <p>Idéer til<br> madkassen</p>
    </div>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schulstad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
              (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-67134920-1', 'auto');
    ga('send', 'pageview');

  </script>
</head>
<body>

<header class="site-header">
  <div class="container">
    <%= link_to root_path do %>
      <div class="logo">
        <p>Madpakkens Dag 2017</p>
        <p>7. september</p>
      </div>
    <% end %>


    <nav class="entry-menu">
      <a href="#" data-id="6" class="<%= 'active' if @active_cat.present? && 6 == @active_cat.id %>">Til læreren</a>
    </nav>

    <nav class="entry-menu">
      <% Category.where.not(id: 6).each do |cat| %>
        <a href="#" data-id="<%= cat.id %>" class="<%= 'active' if cat == @active_cat %>"><%= cat.name %></a>
      <% end %>
    </nav>

    <div style="clear: both;"></div>
  </div>
</header>

<div class="sub-nav container" style="background: #ffffff">
  <% Category.all.each do |cat| %>
    <nav data-id="<%= cat.id %>" class="sub-menu">
      <%# Hardcode recipe links for now. %>
      <% if cat.id == 5 %>
        <%= link_to 'Inspiration og idéer til madpakken', recipes_path %>
      <% end %>

      <% cat.articles.order(:weight).each do |article| %>
        <%= link_to article.title, article_path(article.slug) %>
      <% end %>

      <%# Hardcode contact form link for now. %>
      <% if cat.id == 6 %>
        <%= link_to 'Kontakt', 'mailto:hanne.kragh@lantmannen.com', target: :blank  %>
      <% end %>
    </nav>
  <% end %>
  <div style="clear: both;"></div>
</div>


<div class="container">

  <%= yield :full_width if content_for?(:full_width) %>

  <article <% unless content_for?(:aside) %> class="full-width"<% end %> >
    <%= yield %>
  </article>

  <% unless content_for?(:full_width) %>
    <aside>
      <%= yield :aside %>
    </aside>
  <% end %>

  <footer>
    <div class="logo"></div>

    <% Category.includes(:articles).all.each do |cat| %>
      <nav>
        <a href="#" data-id="<%= cat.id %>"><%= cat.name %></a>

        <nav data-id="<%= cat.id %>">
          <%# Hardcode recipe links for now. %>
          <% if cat.id == 5 %>
            <%= link_to 'Inspiration og ideer til madpakken', recipes_path %>
          <% end %>

          <% cat.articles.each do |article| %>
            <%= link_to article.title, article_path(article) %>
          <% end %>

          <%# Hardcode contact form link for now. %>
          <% if cat.id == 6 %>
            <%= link_to 'Kontakt', 'mailto:hanne.kragh@lantmannen.com', target: :blank  %>
          <% end %>
        </nav>
      </nav>
    <% end %>

    <p class="clearfix">Lantmännen Schulstad A/S   /   Hammerholmen  21-35   /   2650 Hvidovre   /   Tlf +45 36397100</p>
  </footer>
</div>

</body>
</html>

app/views/recipes/index.html.erb
<h1>Inspiration og idéer til madpakker</h1>

<%= image_tag 'opskrifter.png' %>

<p>
  Her finder du masser af opskrifter til den gode madpakke – og hvor du kan få nogle gode ideer til, hvordan netop din frokost skal være så du har noget at glæde dig til når det ringer til spisepause.
</p>
<p>
  Derudover er der også nogle forslag til både mellemmåltid og morgenmaden.
</p>
<p>
  Rigtig god fornøjelse.
</p>

<% RecipeCategory.all.each do |category| %>
  <div class="recipe-category clearfix">
    <h3><%= category.name %></h3>

    <% category.recipes.each do |recipe| %>
      <div class="byline-box open" >
        <a href="#popup-<%= recipe.id %>" class="open-modal">
          <%= image_tag recipe.image_url(:thumb) %>
          <h3><%= recipe.name %></h3>

          <div id="popup-<%= recipe.id %>" class="image-modal image-modal mfp-hide">
            <h3 class="image-modal__header"><%= recipe.name %></h3>

            <%= image_tag recipe.image_url(:full) %>
            <div class="image-modal__description">
              <h3>Det skal du bruge:</h3>
              <p><%= recipe.body.html_safe %></p>
            </div>
            <div class="clearfix"></div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
<% end %>

<% content_for :aside do %>
  <a href="/artikel/madpakkequiz">
    <div class="color-entry-box color-entry-box--small color-entry-box--lunch-quiz">
    </div>
  </a>
  
  <a href="/artikel/motion">
    <div class="color-entry-box color-entry-box--small color-entry-box--blue">
      <h3>Motion</h3>
    </div>
  </a>

  <a href="/artikel/hvad-er-fuldkorn">
    <div class="color-entry-box color-entry-box--small color-entry-box--red">
      <h3>Fuldkorn</h3>
    </div>
  </a>

  <a href="/artikel/energifordeling">
    <div class="color-entry-box color-entry-box--small color-entry-box--green">
      <h3>Maden du<br> spiser</h3>
    </div>
  </a>
<% end %>

app/views/submissions/new.html.erb
<h1>Så er det nu du skal tilmelde din klasse</h1>

<p>For 12. år i træk, opfordrer vi landets skoler til at afholde Madpakkens Dag - med fokus på det sunde måltid midt på dagen.

I år ar vi gjort undervisningsmaterialet webbaseret, således at det kan bruges i hele klassen eller i grupper på elevernes tablets. Der er masser af læring og oplæg til gode dialoger, krydret med gode billeder og interaktiv quiz.

De første 500 klasser der tilmelder sig, får hver leveret 5 pakker brød op til Madpakkens dag 1. september.</p>

<%= form_for @submission do |f| %>

  <% if @submission.errors.count > 0 %>
    <div class="alert alert-danger">
      <h3>Der var følgende fejl i formen</h3>
      <ul>
        <% @submission.errors.messages.each do |attribute, messages| %>
          <% messages.each do |message| %>
            <li><%= attribute %> <%= message %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :school_name, 'Skolens navn' %>
    <%= f.text_field :school_name, class: 'form-control half'  %>
  </div>

  <div class="form-group">
    <%= f.label :contact_person, 'Kontakt person' %>
    <%= f.text_field :contact_person, class: 'form-control half' %>
  </div>

  <div class="form-group">
    <%= f.label :address, 'Adresse' %>
    <%= f.text_field :address, class: 'form-control half'  %>
  </div>

  <div class="form-group">
    <%= f.label :zip, 'Postnr.' %>
    <%= f.text_field :zip, class: 'form-control half'  %>
  </div>

  <div class="form-group">
    <%= f.label :city, 'By' %>
    <%= f.text_field :city, class: 'form-control half'  %>
  </div>

  <div class="form-group">
    <%= f.label :email, 'E-mail' %>
    <%= f.text_field :email, class: 'form-control half'  %>
  </div>

  <div class="form-group">
    <%= f.label :class_level, 'Klassetrin' %>
    <%= f.text_field :class_level, class: 'form-control half'  %>
  </div>

  <div class="form-group">
    <%= f.label :students, 'Antal elever' %>
    <%= f.text_field :students, class: 'form-control half'  %>
  </div>

  <div class="form-group">
    <%= f.label :message, 'Bemærkninger' %>
    <%= f.text_area :message, class: 'form-control', rows: 5, style: 'width: 80%;' %>
  </div>

  <%= f.submit 'Indsend', class: 'btn btn-default' %>
<% end %>

app/views/submissions/success.html.erb
<h1>Tak for din tilmelding</h1>